
development:
  adapter: sqlite3
  database: db/reddit_sinatra_clone_development.db
  host: localhost


production: &default
  adapter: postgresql
  encoding: unicode
  database: production_reddit_sinatra_clone
  host: <%= ENV['DATABASE_HOST'] %>
  username: postgres
  pool: 5




